// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Brand is the golang structure of table brand for DAO operations like Where/Data.
type Brand struct {
	g.Meta      `orm:"table:brand, do:true"`
	Id          interface{} //
	Name        interface{} // 名称
	Logo        interface{} // 图标
	Description interface{} // 简介
	Link        interface{} // 官方链接
	Status      interface{} // 状态：1正常，2禁用
	CreatedAt   *gtime.Time // 创建时间
	UpdatedAt   *gtime.Time // 更新时间
	DeletedAt   *gtime.Time // 删除时间
}
