server:
  # 基本配置
  address: ":8002"
  serverRoot: "public"
  serverAgent: "Go HTTP Server"

  # 接口文档
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

  # 日志扩展配置(参数日志组件配置)
  logger:
    # path: "runtime/logs/"   # 日志文件路径。默认为空，表示关闭，仅输出到终端
    level: "all"
    stdout: true
