// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Brand is the golang structure for table brand.
type Brand struct {
	Id          uint        `json:"id"          ` //
	Name        string      `json:"name"        ` // 名称
	Logo        string      `json:"logo"        ` // 图标
	Description string      `json:"description" ` // 简介
	Link        string      `json:"link"        ` // 官方链接
	Status      string      `json:"status"      ` // 状态：1正常，2禁用
	CreatedAt   *gtime.Time `json:"createdAt"   ` // 创建时间
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` // 更新时间
	DeletedAt   *gtime.Time `json:"deletedAt"   ` // 删除时间
}
